name: Docker CI/CD Site web
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t saidwahidsiteweb .

      - name: Success Message
        run: echo "🎉 Docker image built successfully! 3la slamtk"

